### ISSUE TITLE
Mod IDs fail to resolve

### ISSUE THREAD

**Issue by Jukari** [VazkiiMods/Bliss#113]
Getting an error message when trying to install v1.0.1 that Mod IDs are failing to resolve.  Trying to install modpack with MultiMC, via the zip file download from CurseForge.  Exact error message reads "Unable to resolve mod IDs: Some mod ID resolving tasks failed."  Have redownloaded mod and still get the same error.

**Comment by ifurther** [comment]
I think the error belong CurseForge update its api, and multimc does not support it.

**Comment by Jukari** [comment]
> I think the error belong CurseForge update its api, and CurseForge dose not open api to another application. [Please see](https://github.com/MultiMC/Launcher/issues/4744#issuecomment-1144531406) You could try to download the zip file from github, and new instance with MultiMC and unzip the file in .minecraft dir.

This seems to have worked, made an instance of 1.18.2 with forge 40.1.0, copied the zip file into the instance folder, and it seems to be running correctly.  Thank you.
