### ISSUE TITLE
Running optifine as the faq suggests doesn't work?

### ISSUE THREAD

**Issue by To-2oro** [VazkiiMods/Bliss#119]
The FAQ said to remove Rubidium and Oculus if I wanted to run optifine instead, but it gets stuck loading on the main menu forever when I try to do that! :( not sure what I'm doing wrong...

**Comment by Vazkii** [comment]
You may need to remove something else. Can I see your game log?

**Comment by To-2oro** [comment]
Er, as soon as I figure out where that is ^^; it isn't crashing/creating a crash log, if that's what you mean.

**Comment by Aegide** [comment]
If we assume that :
- you're using [ `curseforge`](https://www.curseforge.com/minecraft/modpacks/bliss)
- the user on your computer is named `to2oro`
- you named your curseforge profile `Bliss`

Then you will be able to find a file named `latest.log` at `C:\Users\to2oro\curseforge\minecraft\Instances\Bliss\logs`.

**Comment by To-2oro** [comment]
Found it thank you, I really hope the issue isn't just that I'm not waiting long enough. [latest.log](https://github.com/VazkiiMods/Bliss/files/8840675/latest.log)

**Comment by To-2oro** [comment]
Um... yeah, the issue was just patience. Sorry. I overreacted because the loading times were longer than running it as default and the progress bar stopped abruptly.
