### ISSUE TITLE
Repeated crash on opening inventory - fresh install

### ISSUE THREAD

**Issue by Justicetom21** [VazkiiMods/Bliss#152]
Just installed 1.0.7 through Prism launcher and made a new world. All I've done is edit my settings/keybinds and turn off shaders (no mod config modifications), but when I searched "Starter" in JEI, after opening my inventory a few times it suddenly crashed. I then re-opened the world and tried to open my inventory again and it crashed. Thanks!
[crash-2022-11-30_22.03.05-client.txt](https://github.com/VazkiiMods/Bliss/files/10122970/crash-2022-11-30_22.03.05-client.txt)

**Comment by Vazkii** [comment]
Looks like just #99
