### ISSUE TITLE
Villagers not interacting with More Villagers Worktables.

### ISSUE THREAD

**Issue by Eziair** [VazkiiMods/Bliss#156]
Bliss version 1.0.7

The villagers I have will interact with the Minecraft workbenches (Lectern, Smiting, Fletching & Cartography) but will not interact with any of the 'More Villagers' tables.

**Comment by Vazkii** [comment]
More Villagers is not in this modpack

**Comment by Eziair** [comment]
Sorry I looked up the wrong mod pack.
